In [54]:
import numpy as np

operator_names = np.array([
    "copy",
    "flip_horizontal",
    "flip_vertical",
    "background",
])

In [55]:
states_0 = np.array([
    ["foreground", "background"],
    ["foreground", "foreground"],
])

states_1 = np.array([
    ["background", "foreground"],
    ["background", "foreground"],
])

states_2 = np.array([
    ["foreground", "foreground"],
    ["background", "background"],
])

In [56]:
candidates_0 = np.array([
    [
        [True,  False, False, False],
        [False, False, False, True ],
    ],
    [
        [True,  False, False, False],
        [True,  True,  False, False],
    ],
])

candidates_1 = np.array([
    [
        [False, False, False, True ],
        [True,  True,  False, False],
    ],
    [
        [False, False, False, True ],
        [True,  False, False, False],
    ],
])

candidates_2 = np.array([
    [
        [True,  False, False, False],
        [True,  False, True,  False],
    ],
    [
        [False, False, False, True ],
        [False, False, False, True ],
    ],
])

In [61]:
all_states = np.stack([states_0, states_1, states_2])
all_candidates = np.stack([candidates_0, candidates_1, candidates_2])
flat_states = all_states.reshape(12)
flat_candidates = all_candidates.reshape(12, 4)
background_mask = (flat_states == 'background')
foreground_mask = (flat_states == 'foreground')
flat_candidates[foreground_mask]

array([[ True, False, False, False],
       [ True, False, False, False],
       [ True,  True, False, False],
       [ True,  True, False, False],
       [ True, False, False, False],
       [ True, False, False, False],
       [ True, False,  True, False]])

In [65]:
foreground_survivors = flat_candidates[foreground_mask].all(axis=0)

In [66]:
foreground_survivors

array([ True, False, False, False])

In [67]:
operator_names[foreground_survivors]

array(['copy'], dtype='<U15')

In [68]:
all_candidates

array([[[[ True, False, False, False],
         [False, False, False,  True]],

        [[ True, False, False, False],
         [ True,  True, False, False]]],


       [[[False, False, False,  True],
         [ True,  True, False, False]],

        [[False, False, False,  True],
         [ True, False, False, False]]],


       [[[ True, False, False, False],
         [ True, False,  True, False]],

        [[False, False, False,  True],
         [False, False, False,  True]]]])